version: "3.9"

services:
  cvital:
    build:
      context: .
      dockerfile: Dockerfile
      target: cvital
    ports:
      - "3000:3000"
    environment:
      atlas_dns_sector_id: 1
      atlas_dns_port: 3000

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cvital
      POSTGRES_PASSWORD: cvital
      POSTGRES_DB: cvital
    volumes:
      - postgresdb:/var/lib/postgresql/data
volumes:
  postgresdb:
    driver: local

