version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: cvital
      POSTGRES_PASSWORD: cvital
      POSTGRES_DB: cvital
    volumes:
      - postgresdb:/var/lib/postgresql/data
volumes:
  postgresdb:
    driver: local

