# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  push:
    tags:    [ "v*" ]

jobs:
  try-to-create-a-release:
    runs-on: ubuntu-latest
      
    steps:
      - name: Create release
        run: curl \
               -X POST \
               -H "Accept:application/vnd.github+json" \
               -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/matthewhunter404/cvital/releases \
               -d '{"tag_name":"${{ github.ref_name }}","target_commitish":"main","name":"${{ github.ref_name }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
